import { MD3LightTheme, MD3DarkTheme, configureFonts } from "react-native-paper";

const fontConfig = {
  fontFamily: "System",
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#1B6EF3",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D6E3FF",
    onPrimaryContainer: "#001B3E",
    secondary: "#00B8A9",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#C5FFF8",
    onSecondaryContainer: "#002E2A",
    tertiary: "#7C5CFC",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#E8DEFF",
    onTertiaryContainer: "#24005A",
    surface: "#FAFCFF",
    onSurface: "#1A1C1E",
    surfaceVariant: "#E0E2EC",
    onSurfaceVariant: "#44474E",
    background: "#FAFCFF",
    onBackground: "#1A1C1E",
    outline: "#74777F",
    outlineVariant: "#C4C6D0",
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: "transparent",
      level1: "#F0F4FF",
      level2: "#E8EEFF",
      level3: "#E0E8FF",
      level4: "#DCE5FF",
      level5: "#D6E0FF",
    },
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#AAC7FF",
    onPrimary: "#002F65",
    primaryContainer: "#00458F",
    onPrimaryContainer: "#D6E3FF",
    secondary: "#7CF8E8",
    onSecondary: "#003731",
    secondaryContainer: "#005048",
    onSecondaryContainer: "#C5FFF8",
    tertiary: "#CFBCFF",
    onTertiary: "#3A0090",
    tertiaryContainer: "#5538C9",
    onTertiaryContainer: "#E8DEFF",
    surface: "#1A1C1E",
    onSurface: "#E3E2E6",
    surfaceVariant: "#44474E",
    onSurfaceVariant: "#C4C6D0",
    background: "#1A1C1E",
    onBackground: "#E3E2E6",
    outline: "#8E9099",
    outlineVariant: "#44474E",
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level0: "transparent",
      level1: "#21242A",
      level2: "#262A32",
      level3: "#2B303A",
      level4: "#2D323C",
      level5: "#303641",
    },
  },
  fonts: configureFonts({ config: fontConfig }),
};
